### ISSUE TITLE
Duplicate entity row created when multiple feature set apply() calls happen asynchronously

### ISSUE THREAD

**Issue by lgvital** [gojek/feast#470] opened 2020-02-11 22:09 UTC
## Expected Behavior 
```
feast=# select * from entities;
                feature_set_id                 | name | project | type  | version 
-----------------------------------------------+------+---------+-------+---------
 0/customer_transactions:1                     | id   | 0       | INT64 |       1
 0/customer_transactions2:1                    | id2  | 0       | INT64 |       1
 0/customer_transactions_with_same_entity_id:1 | id   | 0       | INT64 |       1
(3 rows)
```

## Current Behavior
```
feast=# select * from entities;
                feature_set_id                 | name | project | type  | version 
-----------------------------------------------+------+---------+-------+---------
 0/customer_transactions:1                     | id   | 0       | INT64 |       1
 0/customer_transactions:1                     | id   | 0       | INT64 |       1
 0/customer_transactions2:1                    | id2  | 0       | INT64 |       1
 0/customer_transactions_with_same_entity_id:1 | id   | 0       | INT64 |       1
(4 rows)
```

`client.list_feature_sets()` and `client.list_entities()` also throw the following error:
```
>>> client.list_entities()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/feast/client.py", line 453, in list_entities
    for fs in self.list_feature_sets():
  File "/usr/local/lib/python3.7/site-packages/feast/client.py", line 403, in list_feature_sets
    feature_set = FeatureSet.from_proto(feature_set_proto)
  File "/usr/local/lib/python3.7/site-packages/feast/feature_set.py", line 726, in from_proto
    else feature_set_proto.spec.project,
  File "/usr/local/lib/python3.7/site-packages/feast/feature_set.py", line 63, in __init__
    self.entities = entities
  File "/usr/local/lib/python3.7/site-packages/feast/feature_set.py", line 159, in entities
    self._add_fields(entities)
  File "/usr/local/lib/python3.7/site-packages/feast/feature_set.py", line 309, in _add_fields
    self.add(field)
  File "/usr/local/lib/python3.7/site-packages/feast/feature_set.py", line 275, in add
    + '"'
ValueError: could not add field "id" since it already exists in feature set "customer_transactions"
```

## Steps to reproduce
In local python client create two different feature sets with the same entity name:

```
import pandas as pd
import numpy as np
from pytz import timezone, utc
from feast import Client, Entity, FeatureSet, ValueType
from sdk.python.feast.serving.ServingService_pb2 import GetOnlineFeaturesRequest
from sdk.python.feast.types.Value_pb2 import Value as Value
from google.protobuf.duration_pb2 import Duration
from datetime import datetime, timedelta
from random import randrange
import random
import os


project = '0'
CORE_URL = os.environ.get('FEAST_CORE_URL')
ONLINE_SERVING_URL = os.environ.get('FEAST_ONLINE_SERVING_URL')
BATCH_SERVING_URL = os.environ.get('FEAST_BATCH_SERVING_URL')
client = Client(core_url=CORE_URL, serving_url=BATCH_SERVING_URL) # Connect to Feast Core
client.create_project(project)
client.set_project(project)
days = [datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0).replace(tzinfo=utc) \
        - timedelta(day) for day in range(31)]

# create feature set based on notebook example
customers = [1001, 1002, 1003, 1004, 1005]
customer_features = pd.DataFrame(
    {
        "datetime": [day for day in days for customer in customers],
        "id": [customer for day in days for customer in customers],
        "daily_transactions": [np.random.rand() * 10 for _ in range(len(days) * len(customers))],
        "total_transactions": [np.random.randint(100) for _ in range(len(days) * len(customers))],
    }
)
print(customer_features.head(10))
customer_fs = FeatureSet(
    "customer_transactions",
    max_age=Duration(seconds=86400),
    entities=[Entity(name='id', dtype=ValueType.INT64)]
)
customer_fs.infer_fields_from_df(customer_features, replace_existing_features=True)
client.apply(customer_fs)

# create new feature set with same entity
customers = [1001, 1002, 1003, 1004, 1005]
customer_features = pd.DataFrame(
    {
        "datetime": [day for day in days for customer in customers],
        "id": [customer for day in days for customer in customers],
        "daily_transactions3": [np.random.rand() * 10 for _ in range(len(days) * len(customers))],
        "total_transactions3": [np.random.randint(100) for _ in range(len(days) * len(customers))],
    }
)
print(customer_features.head(10))
customer_fs = FeatureSet(
    "customer_transactions_with_same_entity_id",
    max_age=Duration(seconds=86400),
    entities=[Entity(name='id', dtype=ValueType.INT64)]
)
customer_fs.infer_fields_from_df(customer_features, replace_existing_features=True)
client.apply(customer_fs)
```

### Specifications

- Version: 0.4.4 python client, 0.4.3 installed on GKE cluster.
- Platform: OSX 10.14
- Subsystem: Python 3.7.6

## Possible Solution

* I suppose having the same entity name is an anti-pattern/bad practice and should be avoided given plans for #405, but I'm not clear why this is happening. It's also not clear in the docs that entity *names* should be unique even when changing feature sets.

**Comment by woop** [comment] 2020-02-12 00:30
@lgvital Entity names should not have to be unique. In fact, having the same entity name allows us to join them across feature sets. 

Will try to reproduce this on my side and see where the problem is.

**Comment by lgvital** [comment] 2020-02-12 18:08
Can you clarify what you mean by "they should only be unique inside a project"? Do you mean inside a feature set?

Could a duplicate job be happening during the `apply`? Perhaps something infra related to the GKE/kube setup?

**Comment by lgvital** [comment] 2020-02-12 19:14
It does seem like something wonky/weird is happening during the `apply` call after an `infer_fields_from_df`. I saw this behavior suddenly happen without using an entity of the same name:

```
feast=# select * from entities;
         feature_set_id         |  name   | project | type  | version 
--------------------------------+---------+---------+-------+---------
 0/customer_transactions:1      | id      | 0       | INT64 |       1
 0/customer_transactions:1      | id      | 0       | INT64 |       1
 0/new_customer_transactions:1  | new_id  | 0       | INT64 |       1
 0/new_customer_transactions2:1 | new_id2 | 0       | INT64 |       1
 0/new_customer_transactions3:1 | new_id3 | 0       | INT64 |       1
(5 rows)
```

Will dig into my logs.

**Comment by woop** [comment] 2020-02-13 15:17
> Can you clarify what you mean by "they should only be unique inside a project"? Do you mean inside a feature set?

Right now the only constraint is that fields must be unique within a feature set. Features must also be unique within a project, but entities can be reused.

> Could a duplicate job be happening during the `apply`? Perhaps something infra related to the GKE/kube setup?

My gut feeling is that the problem is closer to the Python SDK.

**Comment by woop** [comment] 2020-02-13 15:38
> It does seem like something wonky/weird is happening during the `apply` call after an `infer_fields_from_df`. I saw this behavior suddenly happen without using an entity of the same name:
> 
> ```
> feast=# select * from entities;
>          feature_set_id         |  name   | project | type  | version 
> --------------------------------+---------+---------+-------+---------
>  0/customer_transactions:1      | id      | 0       | INT64 |       1
>  0/customer_transactions:1      | id      | 0       | INT64 |       1
>  0/new_customer_transactions:1  | new_id  | 0       | INT64 |       1
>  0/new_customer_transactions2:1 | new_id2 | 0       | INT64 |       1
>  0/new_customer_transactions3:1 | new_id3 | 0       | INT64 |       1
> (5 rows)
> ```
> 
> Will dig into my logs.

I launched a 0.4.3 Feast using Docker Compose (admittedly not GKE) and tried to reproduce this error based on your above code snippet. 

All the steps ran fine without any problems.
```
postgres=# select * from entities;
                feature_set_id                 | name | project | type  | version 
-----------------------------------------------+------+---------+-------+---------
 0/customer_transactions:1                     | id   | 0       | INT64 |       1
 0/customer_transactions_with_same_entity_id:1 | id   | 0       | INT64 |       1
(2 rows)
```

The exception that you are receiving in the `list_feature_sets` method and the `list_entities` method typically occurs when there is a name conflict between fields. From your database entries this seems to have happened after a duplicate row has been inserted into the Core database.

What I am trying to figure out is how that happened.

I will try to replicate this on GKE, but I suspect that will make no difference to Docker Compose. 

Could I bother you to perhaps try to run Docker Compose and see if you can replicate this problem? 

Once I can replicate it I should be able to find the problem in the Python SDK or Core.

**Comment by lgvital** [comment] 2020-02-13 22:51
No problem, @woop. Good call to test out docker-compose. I tried setting up a docker-compose environment with 0.4.3 core and ran the above script to try to reproduce. I wasn't able to reproduce in this environment.

```
postgres=# select * from entities;
                feature_set_id                 | name | project | type  | version 
-----------------------------------------------+------+---------+-------+---------
 0/customer_transactions:1                     | id   | 0       | INT64 |       1
 0/customer_transactions_with_same_entity_id:1 | id   | 0       | INT64 |       1

```

Perhaps there is something busted about my 0.4.3 GKE/kube setup then? I can try reproducing from a fresh GKE setup as well.

**Comment by woop** [comment] 2020-02-14 06:07
> No problem, @woop. Good call to test out docker-compose. I tried setting up a docker-compose environment with 0.4.3 core and ran the above script to try to reproduce. I wasn't able to reproduce in this environment.
> 
> ```
> postgres=# select * from entities;
>                 feature_set_id                 | name | project | type  | version 
> -----------------------------------------------+------+---------+-------+---------
>  0/customer_transactions:1                     | id   | 0       | INT64 |       1
>  0/customer_transactions_with_same_entity_id:1 | id   | 0       | INT64 |       1
> ```
> 
> Perhaps there is something busted about my 0.4.3 GKE/kube setup then? I can try reproducing from a fresh GKE setup as well.

Well at least it's working in `Docker Compose`. Would love it if you could try on a fresh deployment of GKE. We are also going to release 0.4.5 quite soon (today or tomorrow). You might want to wait for that.

**Comment by lgvital** [comment] 2020-02-14 23:36
Creating an entity with same name seems to be a red herring.

A fresh GKE install at first did not reproduce the bug, but what actually started the buggy / dupe behavior was our airflow run which has some tasks/operators that create/apply feature sets. I think a way to reproduce the bug in command-line is to have an `apply` call for two different feature sets in the same project happen one after the other (thus having the jobs running nearly in parallel).

@woop Do you use airflow at all at gojek? Do you have any guidance on using airflow with feast? I guess a best practice would be to avoid creating feature sets entirely in airflow dags? I previously assumed the idempotency of `apply` would be no issue for parallel `apply` jobs, but I suppose that's not a fair assumption? FWIW, I could still be off here and the cause could be something else.

**Comment by woop** [comment] 2020-02-15 03:46
> Creating an entity with same name seems to be a red herring.
> 
> A fresh GKE install at first did not reproduce the bug, but what actually started the buggy / dupe behavior was our airflow run which has some tasks/operators that create/apply feature sets. I think a way to reproduce the bug in command-line is to have an `apply` call for two different feature sets in the same project happen one after the other (thus having the jobs running nearly in parallel).

Ok, great! I will try to see if I can replicate this now!

> @woop Do you use airflow at all at gojek? Do you have any guidance on using airflow with feast? I guess a best practice would be to avoid creating feature sets entirely in airflow dags? I previously assumed the idempotency of `apply` would be no issue for parallel `apply` jobs, but I suppose that's not a fair assumption? FWIW, I could still be off here and the cause could be something else.

We use Airflow yes (although we have [abstracted it a bit](https://blog.gojekengineering.com/reliable-ml-pipelines-with-clockwork-34278a11cec6)).

I would advise against running apply commands from within Airflow. Normally you would only be dealing with data (ingest or retrieve) from pipelines. What we do internally is we have a separate repository with our specifications. Changes to this repository are version controlled and applied through CI. That is the only place where changes can happen.

All this being said, the idempotency of applies should in theory still provide you with protection when running this from Airflow. So I am hoping that I can reproduce this on my side.

**Comment by Yanson** [comment] 2020-02-17 09:46
> ...we have a separate repository with our specifications. Changes to this repository are version controlled and applied through CI.

Is any of this open-sourced?

**Comment by woop** [comment] 2020-02-17 10:53
> > ...we have a separate repository with our specifications. Changes to this repository are version controlled and applied through CI.
> 
> Is any of this open-sourced?

Nope, that is Gojek specific IP so we can't open source it. It's basically just .yaml files of the feature set specifications in folders like `dev`, `staging`, `production` and then grouped by system.

**Comment by woop** [comment] 2020-02-22 07:43
@lgvital any luck in reproducing this?

**Comment by lgvital** [comment] 2020-02-28 00:36
Hi @woop, sorry for the late response. Yes, I was able to repro by having an airflow operator that created a featureset from a dataframe like the following:

```
from airflow.contrib.hooks.bigquery_hook import BigQueryHook
from airflow.models import BaseOperator
from faucet_plugin.hooks.feast_hook import FeastHook
from feast import Client, FeatureSet, Entity, ValueType
from google.protobuf.duration_pb2 import Duration


class BigQueryToFeastFeatureSetOperator(BaseOperator):
    def __init__(
            self,
            conn_id: str,
            project: str,
            feature_set_name: str,
            entity_name: str,
            sql: str,
            *args,
            **kwargs
    ):
        super().__init__(*args, **kwargs)
        self.feast_client = FeastHook(conn_id).get_client(project)
        self.project = project
        self.feature_set_name = feature_set_name
        self.entity_name = entity_name
        self.sql = sql
        self.bq = BigQueryHook(use_legacy_sql=False, location='US')

    def execute(self, context):
        features_df = self.bq.get_pandas_df(self.sql)
        fs = FeatureSet(
            self.feature_set_name,
            max_age=Duration(seconds=86400),
            entities=[Entity(name=self.entity_name, dtype=ValueType.INT64)]
        )
        fs.infer_fields_from_df(features_df, replace_existing_features=True)
        self.feast_client.apply(fs)
```

Like you suggested, having feature set creation in your DAG is suboptimal, so I opted to have that be done in a separate script before my DAG runs.  Seems like feature set creations should be idempotent, but I suppose the async nature breaks things. I'll leave it up to you if you think it's worthwhile to keep this issue open! Will rename it to be more accurate.

**Comment by woop** [comment] 2020-02-28 01:01
> Hi @woop, sorry for the late response. Yes, I was able to repro by having an airflow operator that created a featureset from a dataframe like the following:
> 
> ```
> from airflow.contrib.hooks.bigquery_hook import BigQueryHook
> from airflow.models import BaseOperator
> from faucet_plugin.hooks.feast_hook import FeastHook
> from feast import Client, FeatureSet, Entity, ValueType
> from google.protobuf.duration_pb2 import Duration
> 
> 
> class BigQueryToFeastFeatureSetOperator(BaseOperator):
>     def __init__(
>             self,
>             conn_id: str,
>             project: str,
>             feature_set_name: str,
>             entity_name: str,
>             sql: str,
>             *args,
>             **kwargs
>     ):
>         super().__init__(*args, **kwargs)
>         self.feast_client = FeastHook(conn_id).get_client(project)
>         self.project = project
>         self.feature_set_name = feature_set_name
>         self.entity_name = entity_name
>         self.sql = sql
>         self.bq = BigQueryHook(use_legacy_sql=False, location='US')
> 
>     def execute(self, context):
>         features_df = self.bq.get_pandas_df(self.sql)
>         fs = FeatureSet(
>             self.feature_set_name,
>             max_age=Duration(seconds=86400),
>             entities=[Entity(name=self.entity_name, dtype=ValueType.INT64)]
>         )
>         fs.infer_fields_from_df(features_df, replace_existing_features=True)
>         self.feast_client.apply(fs)
> ```
> 
> Like you suggested, having feature set creation in your DAG is suboptimal, so I opted to have that be done in a separate script before my DAG runs. Seems like feature set creations should be idempotent, but I suppose the async nature breaks things. I'll leave it up to you if you think it's worthwhile to keep this issue open! Will rename it to be more accurate.

This is still a known bug. We also ran into it. I tried my best to reproduce it but I simply couldn't.

I am pretty sure the best way to solve this is by fixing the PG data model in Spring. So I will just leave this until a next release where database constraints should eliminate the possibility of running into this.

**Comment by woop** [comment] 2020-03-28 03:07
I believe that this might be resolved already since we have changed the db schemas, but without a way to reproduce this we won't know. 

Closing for now. Lets reopen if we can reproduce the problem.

**Closed by woop** 2020-03-28 03:07 UTC
Labels: kind/bug
